MPNFlights/MPNFlights/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MPNFlights.Models
{
    public class Flight
    {
        public int id { get; set; }
        public Airport From { get; set; }
        public Airport To { get; set; }
        public string DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public string ArrivalDate { get; set; }
        public string ArrivalTime { get; set; }
        public int SeatsAvailable { get; set; }
        public int TicketPrice { get; set; }

    }
}

MPNFlights/MPNFlights/Controllers/FlightsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MPNFlights.Models;
using Neo4jClient;
using Neo4jClient.Cypher;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MPNFlights.Controllers
{
    public class FlightsController : Controller
    {
        private readonly GraphClient client;

        public FlightsController()
        {
            client = new GraphClient(new Uri("http://localhost:7474/db/data"), "neo4j", "boskovic");
            try
            {
                client.Connect();
            }
            catch (Exception exc)
            {
                Console.WriteLine(exc.Message);
            }
        }

        // GET: FlightsController
        public ActionResult Index(QueryFlightsViewModel model)
        {
            if (model != null)
                model = new QueryFlightsViewModel();
            return View();
        }
        public ActionResult Admin(AdminFlightsViewModel model)
        {
            if (!ModelState.IsValid)
            {

            }
            else
            {
                var query = client.Cypher
                    .Match("(n:Airport)-[rel:FLIGHT_TO]->(m:Airport)")
                    .Return((n, rel, m) => new
                    {
                        Od = n.As<Airport>(),
                        Let = rel.As<Flight>(),
                        Do = m.As<Airport>()
                    }).Results.ToList();

                var flights = new List<Flight>(query.Count);


                foreach (var item in query)
                {
                    Flight f = item.Let;
                    f.From = item.Od;
                    f.To = item.Do;
                    flights.Add(f);

                }
                model.FlightsList = flights;
            }


            return View("Admin", model);
        }

        // GET: FlightsController/Details/5
        public ActionResult Details(int id)
        {
            var query = client.Cypher
                  .Match("(n:Airport)")
                  .Where((Airport n) => n.id == id)
                  .Return((n) => new { airport = n.As<Airport>() }).Results;
            Airport a = new Airport();
            foreach (var item in query)
            {
                a = item.airport;
            }
            return View("Details", a);
        }

        // GET: FlightsController/Create
        public ActionResult Create()
        {
            string airport = "";

            Dictionary<string, object> queryDict = new Dictionary<string, object>();
            queryDict.Add("airport", airport);

            var query = new Neo4jClient.Cypher.CypherQuery("MATCH (n:Airport) RETURN n", queryDict, CypherResultMode.Set);
            var airports = ((IRawGraphClient)client).ExecuteGetCypherResults<Airport>(query).ToList();

            CreateFlightViewModel viewModel = new CreateFlightViewModel()
            {
                Airports = airports
            };

            return View(viewModel);
        }

        // POST: FlightsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FlightsController/Edit/5
        public ActionResult Edit(int id)
        {
            var query = client.Cypher
                .Match("(n:Airport)-[rel:FLIGHT_TO]->(m:Airport)")
                .Where((Flight rel) => rel.id == id)
                .Return((n, rel, m) => new
                {
                    Od = n.As<Airport>(),
                    Let = rel.As<Flight>(),
                    Do = m.As<Airport>()
                }).Results.SingleOrDefault();


            CreateFlightViewModel viewModel = new CreateFlightViewModel();

            viewModel.Flight = query.Let;
            viewModel.AirportFromId = query.Od.id;
            viewModel.AirportToId = query.Do.id;
            viewModel.Airports.Add(query.Od);
            viewModel.Airports.Add(query.Do);
            viewModel.Disable = true;

            return View("Create", viewModel);
           
        }

        // POST: FlightsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Save(CreateFlightViewModel model)
        {
            int flightId = model.Flight.id;
            bool disable = model.Disable;
            int airportFrom = model.AirportFromId;
            int airportTo = model.AirportToId;
            string departureDate = model.Flight.DepartureDate;
            string departureTime = model.Flight.DepartureTime;
            string arrivalDate = model.Flight.ArrivalDate;
            string arrivalTime = model.Flight.ArrivalTime;
            int seatsAvailable = model.Flight.SeatsAvailable;
            int ticketPrice = model.Flight.TicketPrice;
            
            Dictionary<string, object> queryDict = new Dictionary<string, object>();
            queryDict.Add("airportFrom", airportFrom);
            queryDict.Add("airportTo", airportTo);
            queryDict.Add("departureDate", departureDate);
            queryDict.Add("departureTime", departureTime);
            queryDict.Add("arrivalDate", arrivalDate);
            queryDict.Add("arrivalTime", arrivalTime);
            queryDict.Add("seatsAvailable", seatsAvailable);
            queryDict.Add("ticketPrice", ticketPrice);
            queryDict.Add("flightId", flightId);

            var queryMax = new Neo4jClient.Cypher.CypherQuery("MATCH ()-[n:FLIGHT_TO]->() RETURN max(n.id)", queryDict, CypherResultMode.Set);
            String maxIdObj = ((IRawGraphClient)client).ExecuteGetCypherResults<String>(queryMax).SingleOrDefault();
            int maxId;
            if (maxIdObj == null)
                maxId = 0;
            else
                maxId = Int32.Parse(maxIdObj);

            var queryFrom = new Neo4jClient.Cypher.CypherQuery("MATCH (n:Airport) WHERE n.id = {airportFrom} RETURN n",
                queryDict, CypherResultMode.Set);
            Airport apFrom = ((IRawGraphClient)client).ExecuteGetCypherResults<Airport>(queryFrom).SingleOrDefault();

            var queryTo = new Neo4jClient.Cypher.CypherQuery("MATCH (n:Airport) WHERE n.id = {airportTo} RETURN n",
                queryDict, CypherResultMode.Set);
            Airport apTo = ((IRawGraphClient)client).ExecuteGetCypherResults<Airport>(queryTo).SingleOrDefault();

            model.Flight.From = apFrom;
            model.Flight.To = apTo;

            QueryFlightsViewModel viewModel = new QueryFlightsViewModel();
            var createQuery = new Neo4jClient.Cypher.CypherQuery("", queryDict, CypherResultMode.Set);

            if (disable == false)
            {
                createQuery = new Neo4jClient.Cypher.CypherQuery("MATCH (n:Airport), (m:Airport) WHERE "
                                                                + "n.id = {airportFrom} AND m.id = {airportTo} "
                                                                + "CREATE (n)-[rel:FLIGHT_TO {id: " + ++maxId
                                                                + " , DepartureDate: '" + departureDate
                                                                + "', DepartureTime: '" + departureTime
                                                                + "', ArrivalDate: '" + arrivalDate
                                                                + "', ArrivalTime: '" + arrivalTime
                                                                + "', SeatsAvailable: " + seatsAvailable
                                                                + ", TicketPrice: " + ticketPrice
                                                                + "}]->(m) RETURN rel", queryDict, CypherResultMode.Set);

            }
            else
            {


                createQuery = new Neo4jClient.Cypher.CypherQuery("MATCH (n:Airport)-[rel:FLIGHT_TO]->(m:Airport) WHERE "
                                                                + "rel.id = {flightId} "
                                                                + "SET rel.DepartureDate = \"" + departureDate
                                                                + "\", rel.DepartureTime = \"" + departureTime
                                                                + "\", rel.ArrivalDate = \"" + arrivalDate
                                                                + "\", rel.ArrivalTime = \"" + arrivalTime
                                                                + "\", rel.SeatsAvailable = " + seatsAvailable
                                                                + ", rel.TicketPrice = " + ticketPrice +
                                                                " RETURN rel", queryDict, CypherResultMode.Set);
            }
                List<Flight> create = ((IRawGraphClient)client).ExecuteGetCypherResults<Flight>(createQuery).ToList();



                var query1 = client.Cypher
                        .Match("(n:Airport)-[rel:FLIGHT_TO]->(m:Airport)")
                        .Return((n, rel, m) => new
                        {
                            Od = n.As<Airport>(),
                            Let = rel.As<Flight>(),
                            Do = m.As<Airport>()
                        }).Results.ToList();

                var flights = new List<Flight>(query1.Count);


                foreach (var item in query1)
                {

MPNFlights/MPNFlights/Views/Flights/Admin.cshtml
@model MPNFlights.Models.AdminFlightsViewModel
@{
    <div>
        <a href="./Create/">Dodaj novi let</a>
    </div>

    <br />

    <div>
        @Html.ActionLink("Aerodromi", "Index", "Airports", new { })
    </div>

    <br />

    <div>
        <table class="table table-bordered">
            <tr class="table-success">
                <th>
                    Od
                </th>
                <th>
                    Do
                </th>
                <th>
                    Datum polaska
                </th>
                <th>
                    Vreme polaska
                </th>
                <th>
                    Datum dolaska
                </th>
                <th>
                    Vreme dolaska
                </th>
                <th>
                    Broj slobodnih mesta
                </th>
                <th>
                    Cena karte (u €)
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model.FlightsList)
            {
             <tr>
                 <td>
                     @Html.ActionLink(item.From.name, "Details", new { id = item.From.id })
                     
                 </td>
                 <td>
                     @Html.ActionLink(item.To.name, "Details", new { id = item.To.id })
                     @*@item.To.name*@
                 </td>
                <td>
                    @item.DepartureDate
                </td>
                <td>
                    @item.DepartureTime
                </td>
                <td>
                    @item.ArrivalDate
                </td>
                <td>
                    @item.ArrivalTime
                </td>
                <td>
                    @item.SeatsAvailable
                </td>
                 <td>
                    @item.TicketPrice
                </td>

                <td>
                    @Html.ActionLink("Izmeni", "Edit", new { id = item.id}) |
                    @Html.ActionLink("Obriši", "Delete", new { id = item.id })
                </td>
             </tr>
            }
        </table>
    </div>
}

MPNFlights/MPNFlights/Views/Flights/Create.cshtml
@model MPNFlights.Models.CreateFlightViewModel
@{
    <form asp-controller="Flights" asp-action="Save" method="post">
        <input hidden asp-for="@Model.Disable" />
        <input hidden asp-for="@Model.Flight.id" />
        <div class="form-group">
            <label>Od:</label>
            <select asp-for="@Model.AirportFromId" asp-items="@(new SelectList(Model.Airports, "id", "fullName"))"
        disabled="@(Model.Disable ? "disabled" : null)"></select>
            @*<select asp-for="@Model.AirportFromId" asp-items="@(new SelectList(Model.Airports, "id", "fullName"))"></select>*@
            <span asp-validation-for="@Model.AirportFromId"></span>
        </div>
        <div class="form-group">
            <label>Do:</label>
            <select asp-for="@Model.AirportToId" asp-items="@(new SelectList(Model.Airports, "id", "fullName"))"
        disabled="@(Model.Disable ? "disabled" : null)"></select>
            @*<select asp-for="@Model.AirportToId" asp-items="@(new SelectList(Model.Airports, "id", "fullName"))"></select>*@
            <span asp-validation-for="@Model.AirportToId"></span>
        </div>
        <div class="form-group">
            <label>Datum polaska:</label>
            <input type="date" asp-for="@Model.Flight.DepartureDate" />
            <span asp-validation-for="@Model.Flight.DepartureDate" />
        </div>
        <div class="form-group">
            <label>Vreme polaska:</label>
            <input type="time" asp-for="@Model.Flight.DepartureTime" />
            <span asp-validation-for="@Model.Flight.DepartureTime" />
        </div>
        <div class="form-group">
            <label>Datum dolaska:</label>
            <input type="date" asp-format="{0:dd.MM.yyyy.}" asp-for="@Model.Flight.ArrivalDate" />
            <span asp-validation-for="@Model.Flight.ArrivalDate" />
        </div>
        <div class="form-group">
            <label>Vreme dolaska:</label>
            <input type="time" asp-for="@Model.Flight.ArrivalTime" />
            <span asp-validation-for="@Model.Flight.ArrivalTime" />
        </div>
        <div class="form-group">
            <label>Slobodnih mesta:</label>
            <input type="number" asp-for="@Model.Flight.SeatsAvailable" />
            <span asp-validation-for="@Model.Flight.SeatsAvailable" />
        </div>
        <div class="form-group">
            <label>Cena karte (u €):</label>
            <input type="number" asp-for="@Model.Flight.TicketPrice" />
            <span asp-validation-for="@Model.Flight.TicketPrice" />
        </div>
        @Html.AntiForgeryToken()

        @if (!Model.Disable)
        {
            <button class="btn btn-primary" type="submit">Dodaj</button>
        }

        else
        {
            <button class="btn btn-primary" type="submit">Sacuvaj</button>
        }
    </form>

}

MPNFlights/MPNFlights/Views/Flights/Details.cshtml
@model MPNFlights.Models.Airport

@{
    ViewData["Title"] = "Details";
}


<div>
    <h4>Aerodrom</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.city)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.city)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.fullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.fullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.country)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Home" asp-action="Index">Vrati se nazad</a>
</div>

MPNFlights/MPNFlights/Views/Flights/Index.cshtml
@model MPNFlights.Models.QueryFlightsViewModel

@{
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>
    }
    <h3>
        Unesite gradove za pretraživanje letova
    </h3>
    using (Html.BeginForm("SearchFlights", "Flights"))
    {

        <div class="form-group">
            <label>Od:</label>
            <input asp-for="@Model.CityFrom" />
            <span asp-validation-for="@Model.CityFrom"></span>
        </div>
        <div class="form-group">
            <label>Do:</label>
            <input asp-for="@Model.CityTo" />
            <span asp-validation-for="@Model.CityTo"></span>
        </div>
        <div class="form-group">
            <label>Datum polaska:</label>
            <input type="date" asp-for="@Model.DepartureDate" />
            <span asp-validation-for="@Model.DepartureDate"></span>
        </div>

        <div class="form-group">
            <label>Pretražite samo direktne letove</label>
            <input type="checkbox" asp-for="@Model.direktnoIliSaPresedanjem" />
        </div>
        <div class="form-group">
            <label>U jednom smeru</label>
            <input type="checkbox" checked asp-for="@Model.jednosmernaKarta" />
        </div>

        <div class="form-group">
            <h5>Popuniti ukoliko želite povratnu kartu</h5>
            <label>Datum povratka:</label>
            <input type="date" asp-for="@Model.ReturnDate" />
            <span asp-validation-for="@Model.ReturnDate"></span>
        </div>

        @Html.AntiForgeryToken();
        <button class="btn btn-primary" type="submit">Pretraži</button>

    }
    <br />

    if (Model != null && Model.FlightsList.Count() > 0)
    {
        <h3> Direktni letovi </h3>
        <div>
            <table class="table table-bordered">
                <tr class="table-success">
                    <th>
                        Od
                    </th>
                    <th>
                        Do
                    </th>
                    <th>
                        Datum polaska
                    </th>
                    <th>
                        Vreme polaska
                    </th>
                    <th>
                        Datum dolaska
                    </th>
                    <th>
                        Vreme dolaska
                    </th>
                    <th>
                        Cena karte (u €)
                    </th>
                    <th>

                    </th>
                </tr>
                @foreach (var item in Model.FlightsList)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.From.name, "Details", new { id = item.From.id })
                            @*@item.From.name*@
                        </td>
                        <td>
                            @Html.ActionLink(item.To.name, "Details", new { id = item.To.id })
                            @*@item.To.name*@
                        </td>
                        <td>
                            @item.DepartureDate
                        </td>
                        <td>
                            @item.DepartureTime
                        </td>
                        <td>
                            @item.ArrivalDate
                        </td>
                        <td>
                            @item.ArrivalTime
                        </td>
                        <td>
                            @item.TicketPrice
                        </td>
                        <td>
                            @Html.ActionLink("Rezerviši", "BookFlight", "Flights", new { id1 = item.id })
                        </td>
                    </tr>
                }
            </table>
        </div>
    }
    else
    {

    }

    if (Model != null && Model.FlightsListBack.Count() > 0)
    {
        <div>
            <table class="table table-bordered">
                <tr class="table-success">
                    <th>
                        Od
                    </th>
                    <th>
                        Do
                    </th>
                    <th>
                        Datum polaska
                    </th>
                    <th>
                        Vreme polaska
                    </th>
                    <th>
                        Datum dolaska
                    </th>
                    <th>
                        Vreme dolaska
                    </th>
                    <th>
                        Cena karte (u €)
                    </th>
                    <th>

                    </th>
                </tr>
                @foreach (var item in Model.FlightsListBack)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.From.name, "Details", new { id = item.From.id })

                        </td>
                        <td>
                            @Html.ActionLink(item.To.name, "Details", new { id = item.To.id })

                        </td>
                        <td>
                            @item.DepartureDate
                        </td>
                        <td>
                            @item.DepartureTime
                        </td>
                        <td>
                            @item.ArrivalDate
                        </td>
                        <td>
                            @item.ArrivalTime
                        </td>
                        <td>
                            @item.TicketPrice
                        </td>
                        <td>
                            @Html.ActionLink("Rezerviši", "BookFlight", "Flights", new { id1 = item.id })
                        </td>
                    </tr>
                }
            </table>
        </div>
    }

    if (Model != null && Model.Presedanja.Count() > 0)
    {
        <h3> Letovi sa presedanjem </h3>
        <div>
            <table class="table table-bordered">
                <tr class="table-success">
                    <th>
                        Od
                    </th>
                    <th>
                        Preko
                    </th>
                    <th>
                        Do
                    </th>
                    <th>
                        Datum polaska
                    </th>
                    <th>
                        Vreme polaska
                    </th>
                    <th>
                        Datum dolaska
                    </th>
                    <th>
                        Vreme dolaska
                    </th>
                    <th>
                        Cena karte (u €)
                    </th>
                    <th>

                    </th>
                </tr>
                @foreach (var item in Model.Presedanja)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Od.name, "Details", new { id = item.Od.id })
                            @*@item.Od.name*@
                        </td>
                        <td>
                            @Html.ActionLink(item.Preko.name, "Details", new { id = item.Preko.id })
                            @*@item.Preko.name*@
                        </td>
                        <td>
                            @Html.ActionLink(item.Do.name, "Details", new { id = item.Do.id })
                            @*@item.Do.name*@
                        </td>
                        <td>
                            @item.LetOdPreko.DepartureDate
                        </td>
                        <td>
                            @item.LetOdPreko.DepartureTime
                        </td>
                        <td>
                            @item.LetPrekoDo.ArrivalDate
                        </td>
                        <td>
                            @item.LetPrekoDo.ArrivalTime
                        </td>
                        <td>
                            @(item.LetOdPreko.TicketPrice + item.LetPrekoDo.TicketPrice)
                        </td>
                        <td>
                            @Html.ActionLink("Rezerviši", "BookFlight", "Flights", new { id1 = item.LetOdPreko.id, id2 = item.LetPrekoDo.id })
                        </td>
                    </tr>
                }
            </table>
        </div>
    }

    if (Model != null && Model.PresedanjaNazad.Count() > 0)
    {
        <div>
            <table class="table table-bordered">
                <tr class="table-success">
                    <th>
                        Od
                    </th>
                    <th>
                        Preko
                    </th>
                    <th>
                        Do
                    </th>
                    <th>
                        Datum polaska
                    </th>
                    <th>
                        Vreme polaska
                    </th>
                    <th>
                        Datum dolaska
                    </th>
                    <th>
                        Vreme dolaska
                    </th>
                    <th>
                        Cena karte (u €)
                    </th>
                    <th>

                    </th>
                </tr>
                @foreach (var item in Model.PresedanjaNazad)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.Od.name, "Details", new { id = item.Od.id })

                        </td>
                        <td>
                            @Html.ActionLink(item.Preko.name, "Details", new { id = item.Preko.id })

                        </td>
                        <td>
                            @Html.ActionLink(item.Do.name, "Details", new { id = item.Do.id })

                        </td>
                        <td>
                            @item.LetOdPreko.DepartureDate
                        </td>
                        <td>
                            @item.LetOdPreko.DepartureTime
                        </td>
                        <td>
                            @item.LetPrekoDo.ArrivalDate
                        </td>
                        <td>
                            @item.LetPrekoDo.ArrivalTime
                        </td>
                        <td>
                            @(item.LetOdPreko.TicketPrice + item.LetPrekoDo.TicketPrice)
                        </td>
                        <td>
                            @Html.ActionLink("Rezerviši", "BookFlight", "Flights", new { id1 = item.LetOdPreko.id, id2 = item.LetPrekoDo.id })
                        </td>
                    </tr>
                }
            </table>
        </div>
    }

}